// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Tag } from '../../../tag/content-types/tag/tag';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum ProjectType {
    Web = 'WEB',
    Game = 'GAME',
    Other = 'OTHER',
}

export interface Project {
    id: number;
    attributes: {
        createdAt: Date;
        updatedAt: Date;
        publishedAt?: Date;
        title: string;
        description?: string;
        video?: { data: Media };
        tags: { data: Tag[] };
        projectType: ProjectType;
        thumbnail: { data: Media };
        link?: string;
        order: number;
    };
}
export interface Project_Plain {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    title: string;
    description?: string;
    video?: Media;
    tags: Tag_Plain[];
    projectType: ProjectType;
    thumbnail: Media;
    link?: string;
    order: number;
}

export interface Project_NoRelations {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    title: string;
    description?: string;
    video?: number;
    tags: number[];
    projectType: ProjectType;
    thumbnail: number;
    link?: string;
    order: number;
}

export interface Project_AdminPanelLifeCycle {
    id: number;
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    title: string;
    description?: string;
    video?: AdminPanelRelationPropertyModification<Media>;
    tags: AdminPanelRelationPropertyModification<Tag_Plain>;
    projectType: ProjectType;
    thumbnail: AdminPanelRelationPropertyModification<Media>;
    link?: string;
    order: number;
}
